### ISSUE TITLE
Suggestion - Log error_description in requestToken

### ISSUE THREAD

**Issue by joezappie** [IhToN/verdaccio-azure-ad-login#2]
Just wanted to provide some feedback on my experience with getting Azure setup correctly for this plugin. I will note before doing this, I've never had any experience with Azure so I've been learning as I go. People more experienced with Azure would probably not run into the small set backs I had.

While trying to get this to work, I kept getting a 401 response from requestToken. I wasn't sure if it was because my config was wrong or if I didn't properly set up something in Azure. I went in and added a console.log(error) to the catch in requestToken. I found that provided a very useful description of what was wrong: error.data.error.error_description. 

I think if this could be logged with verdaccio by default that would greatly aid in future users getting everything setup. It helped guide me through each step to get Azure to allow my application. Here are some examples of the errors_descriptions:

```
 error_description: 'AADSTS7000215: Invalid client secret is provided.\r\n' +
        'Trace ID: a54987ef-9412-4f90-90db-2ae821715d00\r\n' +
        'Correlation ID: 1ade5c99-eea7-4311-9052-5b0397d94d86\r\n' +
        'Timestamp: 2021-02-24 20:15:05Z',
```

```
error_description: "AADSTS65001: The user or administrator has not consented to use the application with ID 'XXXXX' named 'Verdaccio'. Send an interactive authorization request for this user and resource.\r\n" +
        'Trace ID: 83f9eadf-f822-4976-95c5-223524335f00\r\n' +
        'Correlation ID: 339214ad-7976-44dc-adb6-41252c20fcd5\r\n' +
        'Timestamp: 2021-02-24 20:17:58Z',
```

This would be useful at least in debug mode.

Thanks again! This plugin is great and I'm so glad I don't have to make everyone accounts manually with htpasswd.

**Comment by IhToN** [comment]
Hi @jrj2211, thanks for the suggestion!

I've already made the 1.0.5 update, the new catch is:
```javascript
    } catch (error) {
      const errorMsg = error.response?.data?.error_description || error.message || 'Unknown';
      if(error.response?.data) {
        console.debug(error.response.data)
      }
      throw new Error('Failed requesting Azure AD access token: ' + errorMsg);
    }
```

This way we'll show the error_description (or the message if it doesn't exist) in the normal logger and if there is a "debug capturer" listening, it'll display the whole responde data if it exists :)

------------

Small suggestion regarding the user management, if your team is using Teams for the communication you can create specific chat groups to manage package access. Adding and removing the users of the different chat groups will grant and remove such permissions.
This is how we ended up doing it and simplifies the management by a lot.

In case you want to apply this, user groups will be the same as the Teams chat name but without spaces:
Verdaccio => Verdaccio
Verdaccio External => VerdaccioExternal
Verdaccio Admin Group => VerdaccioAdminGroup

------------

If you have any other suggestion or see anything that can be improved don't hesitate to ask, or if you want to, feel free to make such modifications and send a Pull Request :)
