### ISSUE TITLE
Potential security risk.

### ISSUE THREAD

**Issue by DaveMariner** [IhToN/verdaccio-azure-ad-login#4]
The plugin as stands outputs the user's login name and password to logger.debug (in index.ts). 

Couldn't this potentially expose every single user's Active Directory credentials in a plaintext file?

I'm no expert, but it seems as if having this line at least commented out by default (if not removed completely) would be a more secure option in a published package.

**Comment by IhToN** [comment]
Actually you are right, technically speaking the debug messages shouldn't be displayed at all in a production environment but that's prone to human errors.

I am currently away from the computer but I'll push a new version with the line removed ASAP. 

Thanks for the warning!

**Comment by IhToN** [comment]
Sorry for the long delay for such a minor issue.

The log message has been edited according to Dave suggestion.
